### PR TITLE
ElasticSearch 2.4.1 support

### PR DESCRIPTION
**Pull request by vvanholl**
Inspired from PR :
https://github.com/lithiumtech/elasticsearch-consul-discovery/pull/12

Thanks to : https://github.com/digitalkaoz

### CODE REVIEW

**Comment by vvanholl** [comment]
@JigarJoshi, could you look at please ?

**Comment by MiLk** [comment]
I'm also trying to use consul to do the service discovery.

I get the following stacktrace:
```
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]: java.lang.IllegalArgumentException: invalid version format: INTERNAL:DISCOVERY/ZEN/UNICAST
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at org.jboss.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:94)
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at org.jboss.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:62)
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at org.jboss.netty.handler.codec.http.HttpRequestDecoder.createMessage(HttpRequestDecoder.java:75)
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:191)
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:102)
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500)
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipelin
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
Sep 09 09:45:17 elasticsearch001-31a1 elasticsearch[50601]:         at java.lang.Thread.run(Thread.java:745)
```

Are you also having the same error message?

**Comment by vvanholl** [comment]
@MiLk, That's weird, I didn't notice any message like that.

Do you use my code ?

**Comment by MiLk** [comment]
Yes, after more investigations, it might be because the port specified in consul for the service is 9200, I will try to change it to 9300 on Monday.

**Comment by vvanholl** [comment]
That's true !

You must declare port 9300 ( ElasticSearch clustering port) instead of 9200, otherwise nothing works.
I had the same issue when I started using the plugin.

**Comment by MiLk** [comment]
That was issue!

So the PR looks good to me! :shipit:

**Pull request closed without merging**
