### PR TITLE
Elasticsearch 2.1.0 support

### PR DESCRIPTION
**Pull request by vvanholl**

### CODE REVIEW

**Comment by panda87** [comment]
Thanks @vvanholl for the contribution, this is what I look for.
Can someone merge this PR?

**Comment by panda87** [comment]
@vvanholl I tried to setup the plugin with this command
`$ bin/plugin install https://github.com/vvanholl/elasticsearch-consul-discovery/archive/master.zip`
and when I restart ES (2.1.1) I'm getting this exception:
```
ElasticsearchException[Could not find plugin class [org.elasticsearch.plugin.discovery.consul.ConsulDiscoveryPlugin]]; nested: ClassNotFoundException[org.elasticsearch.plugin.discovery.consul.ConsulDiscoveryPlugin];
	at org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:382)
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:348)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:109)
	at org.elasticsearch.node.Node.<init>(Node.java:146)
	at org.elasticsearch.node.Node.<init>(Node.java:128)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.plugin.discovery.consul.ConsulDiscoveryPlugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:380)
	... 8 more
```

Can you pls help me to fix it?

**Comment by JigarJoshi** [comment]
@panda87 Since this is Java plugin (not a Site plugin) you would have to get the source and build the binary by running

    mvn clean install 

and look for the plugin build (`.zip`) in `target/releases/`

https://www.elastic.co/guide/en/elasticsearch/plugins/2.1/intro.html

**Comment by JigarJoshi** [comment]
@vvanholl thanks for PR, could you please also bump up the version of plugin project in `pom.xml` with this PR `2.0`

**Comment by thomasriley** [comment]
Built this from source and can confirm it works with ES 2.1.1.

Thanks @vvanholl & @JigarJoshi :+1:

**Pull request merged**
